### ISSUE TITLE
Last specs V0.9.0 06102018 are not readable

### ISSUE THREAD

**Issue by ustas33** [opencomputeproject/zaius-barreleye-g2#2]
Hello,

I can't open last specs V0.9.0 06102018 in Word or Adobe Acrobat. It's not readable.

Thanks!

**Comment by agangidi53** [comment]
I double checked , and I can read it. Can you try this again ?

**Comment by ustas33** [comment]
Yes, now I can. Maybe something was wrong with me...

Thanks.

**Comment by agangidi53** [comment]
No problem.
